const KEY='roleplay-realm-data';
const seed={characters:[{id:'c1',name:'The Wanderer',avatar:'🦊',description:'A mysterious traveler with a talent for finding strange places.',personality:'Curious, witty, observant, and kind.',appearance:'Dark coat, worn boots, and a silver compass.',backstory:'Nobody knows where they came from.',speech:'Calm, playful, occasionally cryptic.'}],personas:[{id:'p1',name:'Adventurer',avatar:'🧭',description:'A curious version of yourself ready for a story.',personality:'Brave, curious, and quick to help.'}],chats:[]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||seed;let currentChat=null;
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);const save=()=>localStorage.setItem(KEY,JSON.stringify(data));
function go(view){$$('.view').forEach(x=>x.classList.remove('active'));$('#'+view).classList.add('active');$$('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.view===view));render();}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
function card(item,type){return `<article class="card"><div class="avatar">${item.avatar||'✨'}</div><h3>${esc(item.name)}</h3><p>${esc(item.description||item.personality||'No description yet.')}</p><div class="meta">${type==='character'?'Character':'Persona'}</div><div class="card-actions"><button class="secondary-btn" onclick="editItem('${type}','${item.id}')">Edit</button><button class="secondary-btn" onclick="removeItem('${type}','${item.id}')">Delete</button></div></article>`}
function render(){const cg=$('#characterGrid'),pg=$('#personaGrid'),hc=$('#homeCards');if(cg)cg.innerHTML=data.characters.length?data.characters.map(x=>card(x,'character')).join(''):'<div class="empty">No characters yet. Create your first one!</div>';if(pg)pg.innerHTML=data.personas.length?data.personas.map(x=>card(x,'persona')).join(''):'<div class="empty">No personas yet. Create your first one!</div>';if(hc)hc.innerHTML=`<article class="card"><div class="avatar">🎭</div><h3>${data.characters.length} character${data.characters.length===1?'':'s'}</h3><p>Build characters with their own personalities, backstories, and voices.</p></article><article class="card"><div class="avatar">🪪</div><h3>${data.personas.length} persona${data.personas.length===1?'':'s'}</h3><p>Choose who you are in each roleplay.</p></article><article class="card"><div class="avatar">💬</div><h3>${data.chats.length} saved scene${data.chats.length===1?'':'s'}</h3><p>Start a scene and keep your conversations in this browser.</p></article>`;fillSelects()}
function fillSelects(){const c=$('#roleplayCharacter'),p=$('#roleplayPersona');if(!c||!p)return;c.innerHTML=data.characters.map(x=>`<option value="${x.id}">${esc(x.avatar||'✨')} ${esc(x.name)}</option>`).join('');p.innerHTML=data.personas.map(x=>`<option value="${x.id}">${esc(x.avatar||'◉')} ${esc(x.name)}</option>`).join('')}
function openEditor(type,item=null){$('#editorType').value=type;$('#editorTitle').textContent=item?`Edit ${type}`:`New ${type}`;$('#editorEyebrow').textContent=item?'EDIT':'CREATE';$('#fieldName').value=item?.name||'';$('#fieldAvatar').value=item?.avatar||'';$('#fieldDescription').value=item?.description||'';$('#fieldPersonality').value=item?.personality||'';$('#fieldAppearance').value=item?.appearance||'';$('#fieldBackstory').value=item?.backstory||'';$('#fieldSpeech').value=item?.speech||'';$('#editorForm').dataset.id=item?.id||'';$('#editorDialog').showModal()}
$('#newCharacterBtn').onclick=()=>openEditor('character');$('#newPersonaBtn').onclick=()=>openEditor('persona');$('#closeDialog').onclick=()=>$('#editorDialog').close();$('#cancelDialog').onclick=()=>$('#editorDialog').close();
$('#editorForm').addEventListener('submit',e=>{e.preventDefault();const type=$('#editorType').value,id=$('#editorForm').dataset.id||crypto.randomUUID();const obj={id,name:$('#fieldName').value.trim(),avatar:$('#fieldAvatar').value.trim()||'✨',description:$('#fieldDescription').value.trim(),personality:$('#fieldPersonality').value.trim()};if(type==='character'){obj.appearance=$('#fieldAppearance').value.trim();obj.backstory=$('#fieldBackstory').value.trim();obj.speech=$('#fieldSpeech').value.trim()}const list=type==='character'?data.characters:data.personas;const old=list.findIndex(x=>x.id===id);old>=0?list[old]=obj:list.push(obj);save();$('#editorDialog').close();render()});
window.editItem=(type,id)=>openEditor(type,(type==='character'?data.characters:data.personas).find(x=>x.id===id));window.removeItem=(type,id)=>{const list=type==='character'?data.characters:data.personas;const i=list.findIndex(x=>x.id===id);if(i>=0){list.splice(i,1);save();render()}};
$('#beginRoleplay').onclick=()=>{const character=data.characters.find(x=>x.id===$('#roleplayCharacter').value);const persona=data.personas.find(x=>x.id===$('#roleplayPersona').value);if(!character||!persona)return;const scenario=$('#roleplayScenario').value.trim()||'An unexpected adventure begins.';const opening=$('#roleplayOpening').value.trim();currentChat={id:crypto.randomUUID(),characterId:character.id,personaId:persona.id,scenario,messages:[]};if(opening)currentChat.messages.push({role:'ai',text:opening});else currentChat.messages.push({role:'ai',text:character.name+' looks around the scene, waiting for your next move.'});data.chats.unshift(currentChat);save();go('chat');renderChat()};
function renderChat(){if(!currentChat)return;const c=data.characters.find(x=>x.id===currentChat.characterId),p=data.personas.find(x=>x.id===currentChat.personaId);$('#chatTitle').textContent=`${c?.avatar||'✨'} ${c?.name||'Roleplay'}`;$('#messages').innerHTML=currentChat.messages.map(m=>`<div class="message ${m.role}"><div class="role">${m.role==='user'?esc(p?.name||'You'):esc(c?.name||'Character')}</div>${esc(m.text)}</div>`).join('');$('#sceneInfo').innerHTML=`<h3>${esc(c?.name||'Character')}</h3><p><b>Scenario</b><br>${esc(currentChat.scenario)}</p><p><b>Personality</b><br>${esc(c?.personality||'')}</p><p><b>Speech style</b><br>${esc(c?.speech||'Natural')}</p>`;$('#messages').scrollTop=$('#messages').scrollHeight}
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text||!currentChat)return;input.value='';currentChat.messages.push({role:'user',text});renderChat();const character=data.characters.find(x=>x.id===currentChat.characterId);let reply;try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({character,scenario:currentChat.scenario,messages:currentChat.messages})});if(!r.ok)throw new Error('API unavailable');const j=await r.json();reply=j.reply}catch{reply=demoReply(character,text)}currentChat.messages.push({role:'ai',text:reply});save();renderChat()});
function demoReply(c,user){const name=c?.name||'The character';const prompts=['pauses thoughtfully before responding','raises an eyebrow, clearly intrigued','smiles faintly and considers your words','glances toward the scene, then back to you'];return `${name} ${prompts[Math.floor(Math.random()*prompts.length)]}. “${user.length>100?'That gives me a lot to think about. Tell me what you do next.':'Interesting... I want to hear more. What do you do next?'}”`}
$('#backToSetup').onclick=()=>go('roleplay');$('#clearChat').onclick=()=>{if(currentChat){currentChat.messages=[];save();renderChat()}};$('#mobileMenu').onclick=()=>alert('Use the navigation links on the desktop layout, or scroll to choose a section.');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}render();
